Algoritmo "alunoAno"
//  Criar um programa que armazena o nome do aluno em uma variável
//e o ano atual em outra. Em seguida, exibir a seguinte mensagem:
// "Olá, [Nome do Aluno], estamos no ano de 2024".

Var
       anoAtual: inteiro
       nomeAluno: caractere


Inicio
      anoAtual <- 2024
      escreva ("Olá gente boa, qual o seu nome ?")
      leia (nomeAluno)
      escreval ( "Olá, ",nomeAluno,", estamos no ano de ", anoAtual)
      
Fimalgoritmo


