Algoritmo "questao2"
// Escrever um algoritmo que imprima a tabuada de um número
//informado pelo usuário;

Var

   numero, controle: inteiro

Inicio

   controle <- 0
   escreva ("Digite um número para a tabuada: ")
   leia (numero)
   
    enquanto (controle <=10 ) faca
        escreval ( numero, " x ", controle, " = " , numero*controle)
        
        controle := controle + 1
     fimenquanto

Fimalgoritmo