Algoritmo "passagemValor"

Var
  nome: caractere
  procedimento escreverNome(aluno: caractere)
  var
  inicio
      escreval ("procedimento: ", aluno)
      aluno:= "João"
      escreval ("procedimento mod: ", aluno)
      escreval ("principal dentro: ", nome)
      nome:= "Aline"
  fimprocedimento
Inicio
  nome := "Angelo"
  escreverNome("KKKKKKKKris")
  escreval ("principal: ", nome)
  //escreval ("procedimento fora: ", aluno)

Fimalgoritmo