Algoritmo "semnome"
//Escreva um programa que inicializa uma variável inteira com um valor
// fornecido pelo usuário. Em seguida, o programa deve incrementar
// esse valor em 1 e mostrar o resultado. Depois, decrementar
// o valor original em 1 e mostrar o resultado novamente.
Var

    numero: inteiro
    

Inicio

    escreval ("Digite um numero")
    leia (numero)
    
    escreval ("O numero incrementado: ", numero +1)
    escreval ("O numero decrementado: ", numero -1)


Fimalgoritmo