Algoritmo "perimetroRetangulo"
//Desenvolva um algoritmo que calcula e
//mostra o perímetro de um retângulo a partir de sua
// largura e altura fornecidas pelo usuário.
Var

   largura: real
   altura:  real
   perimetro: real
Inicio

     escreval ("Digite a largura do retangulo: ")
     leia (largura)
     escreval ("Digite a altura do retangulo: ")
     leia (altura)
     perimetro <- 2*largura + 2*altura
     escreval ("O primetro é: ", perimetro)

Fimalgoritmo


