Algoritmo "soma2Numeros"
// Escreva um programa no VisualG que solicita ao usuário
//dois números inteiros e, em seguida, exibe a soma desses dois números.

Var

   numero1: inteiro
   numero2: inteiro
   soma: inteiro

Inicio

   escreval ("Digite o 1 numero:")
   leia(numero1)
   escreval ("Digite o 2 numero:")
   leia(numero2)
   soma <- numero1 + numero2
   
   escreval ("A soma é ", soma)

Fimalgoritmo